server:
  port: 8761

spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration       # DB 연결 설정 자동화 끄기
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration  # JPA/Hibernate 자동화 끄기

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    register-with-eureka: false # 자기 자신은 등록 안함
    fetch-registry: false       # 자기 자신한테서 목록 안 가져옴
  server:
    wait-time-in-ms-when-sync-empty: 0  # 서버 시작 대기시간 제거(개발용)